Major migration of CLI to /cli

diff --git a/bin/box b/bin/box
--- a/bin/box
+++ b/bin/box
@@ -1,1 +1,74 @@
-../box
+#!/usr/bin/env bash
+#
+# @todo: http://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
+#
+
+source /opt/box/cli/includes/functions
+source /opt/box/cli/includes/constants
+source "${WPLIB_BOX_COLORS_FILE}"
+
+#
+#
+#if [[ "$1" != "set-user-name" && "$1" != "set-user-email" ]];then
+#
+#    verify_user_config || error=1
+#
+#fi
+
+if [ "" == "${error}" ];then
+
+    if [ "$1" == "" ]; then
+        export WPLIB_BOX_COMMAND="help"
+    else
+        export WPLIB_BOX_COMMAND="$1"
+    fi
+
+    command_file="${WPLIB_BOX_COMMANDS_DIR}/${WPLIB_BOX_COMMAND}"
+
+    if [ "${WPLIB_BOX_COMMAND}" == "help" ]; then
+        source "${command_file}"
+        #check_updates_available "$*"
+        echo 1>&2
+        exit
+    fi
+
+    if [ -f "${command_file}" ]; then
+        command_type="bash"
+    else
+        if [ -f "${command_file}.php" ]; then
+            command_type="php"
+        else
+            echo 1>&2
+            echo -e "\tCommand not found: $1" 1>&2
+            echo 1>&2
+            exit
+        fi
+    fi
+
+    initial_dir=$(pwd)
+    error=0
+    case "${command_type}" in
+       "bash")
+		shift
+            source "${command_file}" "$@"
+            error=$?
+            ;;
+       "php")
+		shift
+
+            /usr/bin/php7.0 "${WPLIB_BOX_INCLUDES_DIR}/run-command.php" --args "${WPLIB_BOX_COMMAND}" "$@"
+            error=$?
+            ;;
+    esac
+    cd "${initial_dir}"
+
+fi
+
+if [[ $error -ne 0 ]]; then
+    echo -e "\t" 1>&2
+    echo "The '$1' command terminated WITH ERRORS." 1>&2
+    echo -e "\t" 1>&2
+    exit 1
+fi
+
+#check_updates_available "$*"
